// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7D79jgcZuiU568FD2ipOUadhs_e1f-ZE',
    appId: '1:920769887092:web:233c56e537493c1a3c0a21',
    messagingSenderId: '920769887092',
    projectId: 'zerohungerr-37d86',
    authDomain: 'zerohungerr-37d86.firebaseapp.com',
    storageBucket: 'zerohungerr-37d86.firebasestorage.app',
    measurementId: 'G-EWMNNGK8YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7vEKhr_XrbLf7JKl4xdy3972v-luvzEQ',
    appId: '1:920769887092:android:c1fbf1ca73537cf03c0a21',
    messagingSenderId: '920769887092',
    projectId: 'zerohungerr-37d86',
    storageBucket: 'zerohungerr-37d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB47C_0F12oPfZ2-cwpaANmtXMS9o10vsc',
    appId: '1:920769887092:ios:3d994c2693ab23ef3c0a21',
    messagingSenderId: '920769887092',
    projectId: 'zerohungerr-37d86',
    storageBucket: 'zerohungerr-37d86.firebasestorage.app',
    iosBundleId: 'com.example.zerohungerr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB47C_0F12oPfZ2-cwpaANmtXMS9o10vsc',
    appId: '1:920769887092:ios:3d994c2693ab23ef3c0a21',
    messagingSenderId: '920769887092',
    projectId: 'zerohungerr-37d86',
    storageBucket: 'zerohungerr-37d86.firebasestorage.app',
    iosBundleId: 'com.example.zerohungerr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7D79jgcZuiU568FD2ipOUadhs_e1f-ZE',
    appId: '1:920769887092:web:5462d3fb2c9f67613c0a21',
    messagingSenderId: '920769887092',
    projectId: 'zerohungerr-37d86',
    authDomain: 'zerohungerr-37d86.firebaseapp.com',
    storageBucket: 'zerohungerr-37d86.firebasestorage.app',
    measurementId: 'G-SHFZNY7CDM',
  );

}